### ISSUE TITLE
add support send messages to telegram topics 

### ISSUE THREAD

**Issue by RRay13** [AlexPokatilov/Harbor-Telegram-Bot#17]
Telegram Bots is support for this feature. 
A chat that has multiple topics inside (technically these are one big chat).
I found the code like this  https://github.com/inCaller/prometheus_bot/pull/101/commits/a11f874b82dbf6500b02adf228e71c5e2ee8104b

Thank you.

**Comment by AprilNEA** [comment]
@RRay13 Check docker image `aprilnea/harbor-telegram-bot` with `-e TOPIC_ID=<thread_id>` in https://github.com/AprilNEA/Harbor-Telegram-Bot, already worked. I will bring up pr after fixing it due to the editor causing excessive line changes

**Comment by AlexPokatilov** [comment]
@AprilNEA Thx for your contribution!
You can fix whitespaces in future, if you want. Or I'll fix it in future releases or a minor commit
